name: Build validation

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
    - name: Install dependencies
      working-directory: ui
      run: npm ci
    - name: Build
      working-directory: ui
      run: npm run build -- --mode selfhosted

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
    - name: Install dependencies
      working-directory: ui
      run: npm ci
    # Lint currently reporting lots of preexisting issues
    # - name: Lint
    #   working-directory: ui
    #   run: npm run lint
